services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # AVAILABILITY SYSTEMS
    #

    OpenDxp\Bundle\EcommerceFrameworkBundle\AvailabilitySystem\AvailabilitySystem: ~
